name: Executar Script 6 Horas

on:
  workflow_dispatch: # Permite ativar com um clique

jobs:
  rodar-script:
    runs-on: ubuntu-latest
    steps:
      - name: Baixar o código do repositório
        uses: actions/checkout@v4

      - name: Dar permissão ao script
        run: chmod +x repetir.sh

      - name: Executar o script por até 6 horas
        run: ./repetir.sh
