      - name: Executar o script do servidor
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Transmite a chave de acesso para o script .sh
        run: |
          ${{ env.SCRIPT_LOCATION }}
